// ── Datos de la app ──────────────────────────────────────────────
// Edita libremente: añade asanas o rutinas siguiendo el mismo formato.

const NIVELES = {
  p: { label: "Principiante", cls: "lvl-p" },
  i: { label: "Intermedio",   cls: "lvl-i" },
  a: { label: "Avanzado",     cls: "lvl-a" },
};

const ASANAS = [
  // ── Principiante ──
  { n: "Tadasana", es: "Postura de la montaña", lvl: "p",
    desc: "Postura de pie fundamental. Enseña la alineación del cuerpo y la respiración consciente.",
    foco: "Postura y enraizamiento" },
  { n: "Balasana", es: "Postura del niño", lvl: "p",
    desc: "Postura de descanso que estira la espalda baja, las caderas y calma el sistema nervioso.",
    foco: "Relajación y descanso" },
  { n: "Adho Mukha Svanasana", es: "Perro boca abajo", lvl: "p",
    desc: "Estira toda la cadena posterior y fortalece brazos y hombros. Una postura que se repite mucho.",
    foco: "Fuerza y flexibilidad" },
  { n: "Marjaryasana–Bitilasana", es: "Gato–Vaca", lvl: "p",
    desc: "Movimiento fluido entre flexión y extensión de columna, sincronizado con la respiración.",
    foco: "Movilidad de columna" },
  { n: "Sukhasana", es: "Postura fácil", lvl: "p",
    desc: "Sentada con piernas cruzadas para meditación y respiración. Base de la práctica sentada.",
    foco: "Meditación" },

  // ── Intermedio ──
  { n: "Virabhadrasana II", es: "Guerrero II", lvl: "i",
    desc: "Postura de pie que abre las caderas y fortalece piernas, brazos y concentración.",
    foco: "Fuerza de piernas" },
  { n: "Trikonasana", es: "Triángulo", lvl: "i",
    desc: "Estiramiento lateral profundo que mejora el equilibrio y abre el pecho.",
    foco: "Apertura lateral" },
  { n: "Vrksasana", es: "Postura del árbol", lvl: "i",
    desc: "Equilibrio sobre una pierna. Desarrolla concentración, estabilidad y calma.",
    foco: "Equilibrio" },
  { n: "Setu Bandhasana", es: "Puente", lvl: "i",
    desc: "Flexión suave hacia atrás que fortalece glúteos y espalda, y abre el pecho.",
    foco: "Apertura de pecho" },
  { n: "Bhujangasana", es: "Cobra", lvl: "i",
    desc: "Extensión de columna que fortalece la espalda y abre el frente del cuerpo.",
    foco: "Fuerza de espalda" },

  // ── Avanzado ──
  { n: "Bakasana", es: "Postura del cuervo", lvl: "a",
    desc: "Equilibrio sobre las manos. Exige fuerza de core, muñecas y mucha concentración.",
    foco: "Equilibrio en brazos" },
  { n: "Sirsasana", es: "Postura sobre la cabeza", lvl: "a",
    desc: "La 'reina' de las asanas. Inversión que requiere control total y práctica progresiva.",
    foco: "Inversión completa" },
  { n: "Chakrasana", es: "Postura de la rueda", lvl: "a",
    desc: "Flexión hacia atrás profunda que exige flexibilidad de columna y fuerza de brazos.",
    foco: "Extensión profunda" },
  { n: "Eka Pada Rajakapotasana", es: "Paloma real", lvl: "a",
    desc: "Apertura intensa de caderas combinada con flexión hacia atrás. Requiere preparación previa.",
    foco: "Apertura de caderas" },
];

// Cada paso tiene: t (nombre), dur (texto de duración), pose (clave de POSES)
// y como (qué hay que hacer, explicado para quien empieza).
const RUTINAS = [
  { t: "Despertar suave", lvl: "p", min: 15,
    pasos: [
      { t: "Sukhasana y respiración", dur: "3 min", min: 3, pose: "Sukhasana",
        como: "Siéntate en el suelo con las piernas cruzadas, la espalda recta y las manos sobre las rodillas. Cierra los ojos y respira lento por la nariz, notando cómo el aire entra y sale." },
      { t: "Gato–Vaca", dur: "2 min", min: 2, pose: "Marjaryasana–Bitilasana",
        como: "Ponte a cuatro patas. Al inhalar, hunde la espalda y mira al frente (vaca); al exhalar, redondea la espalda y deja caer la cabeza (gato). Repite siguiendo tu respiración." },
      { t: "Perro boca abajo", dur: "2 min", min: 2, pose: "Adho Mukha Svanasana",
        como: "Desde cuatro patas, eleva las caderas hasta formar una V invertida. Empuja el suelo con las manos y relaja la cabeza. Puedes mantener las rodillas dobladas." },
      { t: "Postura del niño", dur: "2 min", min: 2, pose: "Balasana",
        como: "Arrodíllate, siéntate sobre los talones y pliega el cuerpo hacia delante con los brazos estirados. Apoya la frente en el suelo y descansa." },
      { t: "Respiración final", dur: "6 min", min: 6, pose: "Savasana",
        como: "Túmbate boca arriba con brazos y piernas relajados. Respira de forma natural y deja que todo el cuerpo se suelte." },
    ] },
  { t: "Base de pie", lvl: "p", min: 20,
    pasos: [
      { t: "Tadasana", dur: "2 min", min: 2, pose: "Tadasana",
        como: "De pie, con los pies juntos y los brazos a los lados. Reparte el peso entre ambos pies, alarga la columna y respira tranquilo." },
      { t: "Saludo al sol suave", dur: "6 min", min: 6, pose: "Surya Namaskar",
        como: "Secuencia fluida: inhala subiendo los brazos, exhala plegándote hacia delante, pasa por el perro boca abajo y vuelve a ponerte de pie. Repite a tu ritmo, sin prisa." },
      { t: "Guerrero (preparación)", dur: "4 min", min: 4, pose: "Virabhadrasana II",
        como: "Da un paso largo hacia atrás, dobla la rodilla delantera y abre los brazos en cruz. Mantén unas respiraciones y cambia de lado." },
      { t: "Postura del niño", dur: "3 min", min: 3, pose: "Balasana",
        como: "Arrodíllate, siéntate sobre los talones y pliega el cuerpo hacia delante. Apoya la frente en el suelo y descansa." },
      { t: "Descanso", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba, cierra los ojos y respira con calma hasta terminar la sesión." },
    ] },
  { t: "Fuerza y equilibrio", lvl: "i", min: 25,
    pasos: [
      { t: "Saludo al sol", dur: "5 min", min: 5, pose: "Surya Namaskar",
        como: "Encadena varios saludos al sol para calentar el cuerpo: brazos arriba, pliegue hacia delante, perro boca abajo y vuelta de pie." },
      { t: "Guerrero II", dur: "3 min por lado", min: 6, pose: "Virabhadrasana II",
        como: "Piernas muy separadas, rodilla delantera doblada sobre el tobillo y brazos en cruz. Mirada al frente, hombros relajados. Cambia de lado." },
      { t: "Triángulo", dur: "3 min", min: 3, pose: "Trikonasana",
        como: "Con las piernas abiertas y estiradas, inclina el tronco hacia la pierna delantera y apoya la mano en la espinilla o el tobillo. El otro brazo sube hacia el techo." },
      { t: "Árbol", dur: "3 min", min: 3, pose: "Vrksasana",
        como: "Apoya la planta de un pie en el interior de la otra pierna (nunca sobre la rodilla) y junta las manos. Fija la mirada en un punto para no perder el equilibrio." },
      { t: "Puente", dur: "3 min", min: 3, pose: "Setu Bandhasana",
        como: "Túmbate boca arriba con las rodillas dobladas y los pies cerca de los glúteos. Presiona los pies contra el suelo y eleva las caderas." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba, suelta todo el cuerpo y respira de forma natural para cerrar la práctica." },
    ] },
  { t: "Apertura de cadera", lvl: "i", min: 30,
    pasos: [
      { t: "Calentamiento", dur: "5 min", min: 5, pose: "Marjaryasana–Bitilasana",
        como: "Moviliza el cuerpo con suavidad: Gato–Vaca, círculos de cadera y algún saludo al sol tranquilo." },
      { t: "Guerrero II + Triángulo", dur: "8 min", min: 8, pose: "Virabhadrasana II",
        como: "Encadena Guerrero II y Triángulo en el mismo lado, mantén varias respiraciones en cada postura y después cambia de lado." },
      { t: "Cobra", dur: "4 min", min: 4, pose: "Bhujangasana",
        como: "Túmbate boca abajo con las manos bajo los hombros. Al inhalar, despega el pecho del suelo sin forzar la zona lumbar." },
      { t: "Puente", dur: "4 min", min: 4, pose: "Setu Bandhasana",
        como: "Boca arriba, rodillas dobladas y pies firmes en el suelo. Eleva las caderas y mantén respirando." },
      { t: "Estiramientos finales", dur: "4 min", min: 4, pose: "Uttanasana",
        como: "De pie, pliégate suavemente hacia delante dejando colgar el tronco y los brazos. Mantén las rodillas un poco dobladas." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba y descansa, dejando que el cuerpo integre la práctica." },
    ] },
  { t: "Práctica avanzada", lvl: "a", min: 40,
    pasos: [
      { t: "Calentamiento dinámico", dur: "8 min", min: 8, pose: "Surya Namaskar",
        como: "Varios saludos al sol encadenados para subir la temperatura y preparar muñecas, hombros y caderas." },
      { t: "Postura del cuervo", dur: "6 min", min: 6, pose: "Bakasana",
        como: "En cuclillas, apoya las manos en el suelo, lleva las rodillas a la parte alta de los brazos y traslada el peso hacia delante hasta despegar los pies." },
      { t: "Postura sobre la cabeza", dur: "6 min", min: 6, pose: "Sirsasana",
        como: "Apoya antebrazos y coronilla en el suelo, camina con los pies hacia la cabeza y sube las piernas con control. Al principio, practica junto a una pared." },
      { t: "Rueda", dur: "5 min", min: 5, pose: "Chakrasana",
        como: "Túmbate boca arriba, apoya las manos junto a las orejas y los pies en el suelo, y empuja para elevar todo el cuerpo en arco." },
      { t: "Paloma real", dur: "7 min", min: 7, pose: "Eka Pada Rajakapotasana",
        como: "Desde cuatro patas, lleva una rodilla hacia delante y estira la otra pierna hacia atrás. Mantén las caderas niveladas y pliégate o incorpórate según tu nivel." },
      { t: "Savasana", dur: "8 min", min: 8, pose: "Savasana",
        como: "Descanso final completo, boca arriba, dejando que el cuerpo asimile el trabajo." },
    ] },
];
