// ── Datos de la app ──────────────────────────────────────────────
// Edita libremente: añade asanas o rutinas siguiendo el mismo formato.

const NIVELES = {
  p: { label: "Principiante", cls: "lvl-p" },
  i: { label: "Intermedio",   cls: "lvl-i" },
  a: { label: "Avanzado",     cls: "lvl-a" },
};

const ASANAS = [
  // ── Principiante ──
  { n: "Tadasana", es: "Postura de la montaña", lvl: "p",
    desc: "Postura de pie fundamental. Enseña la alineación del cuerpo y la respiración consciente.",
    foco: "Postura y enraizamiento" },
  { n: "Balasana", es: "Postura del niño", lvl: "p",
    desc: "Postura de descanso que estira la espalda baja, las caderas y calma el sistema nervioso.",
    foco: "Relajación y descanso" },
  { n: "Adho Mukha Svanasana", es: "Perro boca abajo", lvl: "p",
    desc: "Estira toda la cadena posterior y fortalece brazos y hombros. Una postura que se repite mucho.",
    foco: "Fuerza y flexibilidad" },
  { n: "Marjaryasana–Bitilasana", es: "Gato–Vaca", lvl: "p",
    desc: "Movimiento fluido entre flexión y extensión de columna, sincronizado con la respiración.",
    foco: "Movilidad de columna" },
  { n: "Sukhasana", es: "Postura fácil", lvl: "p",
    desc: "Sentada con piernas cruzadas para meditación y respiración. Base de la práctica sentada.",
    foco: "Meditación" },
  { n: "Savasana", es: "Postura del cadáver", lvl: "p",
    desc: "Tumbada boca arriba con todo el cuerpo relajado. Cierra cada práctica e integra sus beneficios.",
    foco: "Relajación profunda" },
  { n: "Uttanasana", es: "Pinza de pie", lvl: "p",
    desc: "Flexión hacia delante de pie que estira toda la cadena posterior y calma la mente.",
    foco: "Estiramiento posterior" },
  { n: "Paschimottanasana", es: "Pinza sentada", lvl: "p",
    desc: "Sentada con las piernas estiradas, el tronco se pliega sobre ellas. Estira espalda e isquios.",
    foco: "Flexibilidad posterior" },
  { n: "Supta Matsyendrasana", es: "Torsión tumbada", lvl: "p",
    desc: "Torsión suave en el suelo que libera la zona lumbar y ayuda a la digestión.",
    foco: "Torsión y descarga lumbar" },
  { n: "Anjaneyasana", es: "Luna creciente", lvl: "p",
    desc: "Zancada baja con la rodilla trasera apoyada. Abre las caderas y el pecho.",
    foco: "Apertura de cadera y pecho" },

  // ── Intermedio ──
  { n: "Virabhadrasana II", es: "Guerrero II", lvl: "i",
    desc: "Postura de pie que abre las caderas y fortalece piernas, brazos y concentración.",
    foco: "Fuerza de piernas" },
  { n: "Trikonasana", es: "Triángulo", lvl: "i",
    desc: "Estiramiento lateral profundo que mejora el equilibrio y abre el pecho.",
    foco: "Apertura lateral" },
  { n: "Vrksasana", es: "Postura del árbol", lvl: "i",
    desc: "Equilibrio sobre una pierna. Desarrolla concentración, estabilidad y calma.",
    foco: "Equilibrio" },
  { n: "Setu Bandhasana", es: "Puente", lvl: "i",
    desc: "Flexión suave hacia atrás que fortalece glúteos y espalda, y abre el pecho.",
    foco: "Apertura de pecho" },
  { n: "Bhujangasana", es: "Cobra", lvl: "i",
    desc: "Extensión de columna que fortalece la espalda y abre el frente del cuerpo.",
    foco: "Fuerza de espalda" },
  { n: "Virabhadrasana I", es: "Guerrero I", lvl: "i",
    desc: "Zancada con la cadera al frente y los brazos al cielo. Fuerza, enfoque y apertura.",
    foco: "Fuerza y enfoque" },
  { n: "Virabhadrasana III", es: "Guerrero III", lvl: "i",
    desc: "Equilibrio sobre una pierna con el cuerpo en T. Exige estabilidad y core.",
    foco: "Equilibrio y core" },
  { n: "Utkatasana", es: "Postura de la silla", lvl: "i",
    desc: "Como sentarse en una silla invisible con los brazos arriba. Quema y fortalece las piernas.",
    foco: "Fuerza de piernas" },
  { n: "Phalakasana", es: "Plancha", lvl: "i",
    desc: "Cuerpo recto sostenido sobre manos y pies. La base de la fuerza del core.",
    foco: "Core y brazos" },
  { n: "Navasana", es: "Postura de la barca", lvl: "i",
    desc: "En equilibrio sobre los glúteos con piernas y tronco en V. Abdomen fuerte y estable.",
    foco: "Core profundo" },
  { n: "Ardha Matsyendrasana", es: "Torsión sentada", lvl: "i",
    desc: "Torsión profunda de columna sentada. Mejora la movilidad y masajea los órganos internos.",
    foco: "Movilidad de columna" },

  // ── Avanzado ──
  { n: "Bakasana", es: "Postura del cuervo", lvl: "a",
    desc: "Equilibrio sobre las manos. Exige fuerza de core, muñecas y mucha concentración.",
    foco: "Equilibrio en brazos" },
  { n: "Sirsasana", es: "Postura sobre la cabeza", lvl: "a",
    desc: "La 'reina' de las asanas. Inversión que requiere control total y práctica progresiva.",
    foco: "Inversión completa" },
  { n: "Chakrasana", es: "Postura de la rueda", lvl: "a",
    desc: "Flexión hacia atrás profunda que exige flexibilidad de columna y fuerza de brazos.",
    foco: "Extensión profunda" },
  { n: "Eka Pada Rajakapotasana", es: "Paloma real", lvl: "a",
    desc: "Apertura intensa de caderas combinada con flexión hacia atrás. Requiere preparación previa.",
    foco: "Apertura de caderas" },
  { n: "Salamba Sarvangasana", es: "Postura de la vela", lvl: "a",
    desc: "Inversión sobre los hombros con las piernas al cielo. Calma el sistema nervioso.",
    foco: "Inversión y calma" },
  { n: "Halasana", es: "Postura del arado", lvl: "a",
    desc: "Desde la vela, los pies bajan al suelo por detrás de la cabeza. Estiramiento intenso de espalda.",
    foco: "Estiramiento de columna" },
  { n: "Hanumanasana", es: "Espagat del mono", lvl: "a",
    desc: "Apertura completa de piernas hacia delante y atrás. Exige años de flexibilidad progresiva.",
    foco: "Flexibilidad máxima" },
  { n: "Adho Mukha Vrksasana", es: "El pino", lvl: "a",
    desc: "Equilibrio invertido sobre las manos. Fuerza, control y confianza. Empieza junto a una pared.",
    foco: "Equilibrio invertido" },
];

// Cada paso tiene: t (nombre), dur (texto de duración), pose (clave de POSES)
// y como (qué hay que hacer, explicado para quien empieza).
const RUTINAS = [
  { t: "Despertar suave", lvl: "p", min: 15,
    pasos: [
      { t: "Sukhasana y respiración", dur: "3 min", min: 3, pose: "Sukhasana",
        como: "Siéntate en el suelo con las piernas cruzadas, la espalda recta y las manos sobre las rodillas. Cierra los ojos y respira lento por la nariz, notando cómo el aire entra y sale." },
      { t: "Gato–Vaca", dur: "2 min", min: 2, pose: "Marjaryasana–Bitilasana",
        como: "Ponte a cuatro patas. Al inhalar, hunde la espalda y mira al frente (vaca); al exhalar, redondea la espalda y deja caer la cabeza (gato). Repite siguiendo tu respiración." },
      { t: "Perro boca abajo", dur: "2 min", min: 2, pose: "Adho Mukha Svanasana",
        como: "Desde cuatro patas, eleva las caderas hasta formar una V invertida. Empuja el suelo con las manos y relaja la cabeza. Puedes mantener las rodillas dobladas." },
      { t: "Postura del niño", dur: "2 min", min: 2, pose: "Balasana",
        como: "Arrodíllate, siéntate sobre los talones y pliega el cuerpo hacia delante con los brazos estirados. Apoya la frente en el suelo y descansa." },
      { t: "Respiración final", dur: "6 min", min: 6, pose: "Savasana",
        como: "Túmbate boca arriba con brazos y piernas relajados. Respira de forma natural y deja que todo el cuerpo se suelte." },
    ] },
  { t: "Base de pie", lvl: "p", min: 20,
    pasos: [
      { t: "Tadasana", dur: "2 min", min: 2, pose: "Tadasana",
        como: "De pie, con los pies juntos y los brazos a los lados. Reparte el peso entre ambos pies, alarga la columna y respira tranquilo." },
      { t: "Saludo al sol suave", dur: "6 min", min: 6, pose: "Surya Namaskar",
        como: "Secuencia fluida: inhala subiendo los brazos, exhala plegándote hacia delante, pasa por el perro boca abajo y vuelve a ponerte de pie. Repite a tu ritmo, sin prisa." },
      { t: "Guerrero (preparación)", dur: "4 min", min: 4, pose: "Virabhadrasana II",
        como: "Da un paso largo hacia atrás, dobla la rodilla delantera y abre los brazos en cruz. Mantén unas respiraciones y cambia de lado." },
      { t: "Postura del niño", dur: "3 min", min: 3, pose: "Balasana",
        como: "Arrodíllate, siéntate sobre los talones y pliega el cuerpo hacia delante. Apoya la frente en el suelo y descansa." },
      { t: "Descanso", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba, cierra los ojos y respira con calma hasta terminar la sesión." },
    ] },
  { t: "Fuerza y equilibrio", lvl: "i", min: 25,
    pasos: [
      { t: "Saludo al sol", dur: "5 min", min: 5, pose: "Surya Namaskar",
        como: "Encadena varios saludos al sol para calentar el cuerpo: brazos arriba, pliegue hacia delante, perro boca abajo y vuelta de pie." },
      { t: "Guerrero II", dur: "3 min por lado", min: 6, pose: "Virabhadrasana II",
        como: "Piernas muy separadas, rodilla delantera doblada sobre el tobillo y brazos en cruz. Mirada al frente, hombros relajados. Cambia de lado." },
      { t: "Triángulo", dur: "3 min", min: 3, pose: "Trikonasana",
        como: "Con las piernas abiertas y estiradas, inclina el tronco hacia la pierna delantera y apoya la mano en la espinilla o el tobillo. El otro brazo sube hacia el techo." },
      { t: "Árbol", dur: "3 min", min: 3, pose: "Vrksasana",
        como: "Apoya la planta de un pie en el interior de la otra pierna (nunca sobre la rodilla) y junta las manos. Fija la mirada en un punto para no perder el equilibrio." },
      { t: "Puente", dur: "3 min", min: 3, pose: "Setu Bandhasana",
        como: "Túmbate boca arriba con las rodillas dobladas y los pies cerca de los glúteos. Presiona los pies contra el suelo y eleva las caderas." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba, suelta todo el cuerpo y respira de forma natural para cerrar la práctica." },
    ] },
  { t: "Apertura de cadera", lvl: "i", min: 30,
    pasos: [
      { t: "Calentamiento", dur: "5 min", min: 5, pose: "Marjaryasana–Bitilasana",
        como: "Moviliza el cuerpo con suavidad: Gato–Vaca, círculos de cadera y algún saludo al sol tranquilo." },
      { t: "Guerrero II + Triángulo", dur: "8 min", min: 8, pose: "Virabhadrasana II",
        como: "Encadena Guerrero II y Triángulo en el mismo lado, mantén varias respiraciones en cada postura y después cambia de lado." },
      { t: "Cobra", dur: "4 min", min: 4, pose: "Bhujangasana",
        como: "Túmbate boca abajo con las manos bajo los hombros. Al inhalar, despega el pecho del suelo sin forzar la zona lumbar." },
      { t: "Puente", dur: "4 min", min: 4, pose: "Setu Bandhasana",
        como: "Boca arriba, rodillas dobladas y pies firmes en el suelo. Eleva las caderas y mantén respirando." },
      { t: "Estiramientos finales", dur: "4 min", min: 4, pose: "Uttanasana",
        como: "De pie, pliégate suavemente hacia delante dejando colgar el tronco y los brazos. Mantén las rodillas un poco dobladas." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Túmbate boca arriba y descansa, dejando que el cuerpo integre la práctica." },
    ] },
  { t: "Práctica avanzada", lvl: "a", min: 40,
    pasos: [
      { t: "Calentamiento dinámico", dur: "8 min", min: 8, pose: "Surya Namaskar",
        como: "Varios saludos al sol encadenados para subir la temperatura y preparar muñecas, hombros y caderas." },
      { t: "Postura del cuervo", dur: "6 min", min: 6, pose: "Bakasana",
        como: "En cuclillas, apoya las manos en el suelo, lleva las rodillas a la parte alta de los brazos y traslada el peso hacia delante hasta despegar los pies." },
      { t: "Postura sobre la cabeza", dur: "6 min", min: 6, pose: "Sirsasana",
        como: "Apoya antebrazos y coronilla en el suelo, camina con los pies hacia la cabeza y sube las piernas con control. Al principio, practica junto a una pared." },
      { t: "Rueda", dur: "5 min", min: 5, pose: "Chakrasana",
        como: "Túmbate boca arriba, apoya las manos junto a las orejas y los pies en el suelo, y empuja para elevar todo el cuerpo en arco." },
      { t: "Paloma real", dur: "7 min", min: 7, pose: "Eka Pada Rajakapotasana",
        como: "Desde cuatro patas, lleva una rodilla hacia delante y estira la otra pierna hacia atrás. Mantén las caderas niveladas y pliégate o incorpórate según tu nivel." },
      { t: "Savasana", dur: "8 min", min: 8, pose: "Savasana",
        como: "Descanso final completo, boca arriba, dejando que el cuerpo asimile el trabajo." },
    ] },
  { t: "Yoga para dormir", lvl: "p", min: 20,
    pasos: [
      { t: "Respiración sentada", dur: "3 min", min: 3, pose: "Sukhasana",
        como: "Siéntate con las piernas cruzadas, apaga las luces fuertes y respira alargando cada exhalación, como si soplaras una vela muy despacio." },
      { t: "Gato–Vaca lento", dur: "3 min", min: 3, pose: "Marjaryasana–Bitilasana",
        como: "A cuatro patas, mueve la columna muy despacio al ritmo de la respiración, soltando la tensión del día." },
      { t: "Pinza sentada", dur: "4 min", min: 4, pose: "Paschimottanasana",
        como: "Sentado con las piernas estiradas, pliégate hacia delante sin forzar y deja caer la cabeza. Puedes doblar las rodillas." },
      { t: "Torsión tumbada", dur: "4 min", min: 4, pose: "Supta Matsyendrasana",
        como: "Boca arriba, lleva las rodillas hacia un lado y los brazos en cruz. Mantén 2 minutos y cambia de lado." },
      { t: "Savasana", dur: "6 min", min: 6, pose: "Savasana",
        como: "Túmbate boca arriba, tápate si hace fresco y deja que el cuerpo se hunda en el suelo. Respira sin controlar nada." },
    ] },
  { t: "Espalda sana", lvl: "p", min: 20,
    pasos: [
      { t: "Gato–Vaca", dur: "4 min", min: 4, pose: "Marjaryasana–Bitilasana",
        como: "A cuatro patas, alterna arquear y redondear la columna con calma, vértebra a vértebra." },
      { t: "Cobra suave", dur: "3 min", min: 3, pose: "Bhujangasana",
        como: "Boca abajo, manos bajo los hombros. Eleva el pecho solo hasta donde no haya molestia lumbar, y baja despacio. Repite varias veces." },
      { t: "Postura del niño", dur: "3 min", min: 3, pose: "Balasana",
        como: "Siéntate sobre los talones y pliégate hacia delante. Nota cómo se estira y descansa la espalda baja." },
      { t: "Torsión tumbada", dur: "4 min", min: 4, pose: "Supta Matsyendrasana",
        como: "Boca arriba, deja caer las rodillas a un lado manteniendo los hombros en el suelo. Cambia de lado a mitad." },
      { t: "Puente", dur: "3 min", min: 3, pose: "Setu Bandhasana",
        como: "Eleva las caderas presionando los pies en el suelo, mantén unas respiraciones y baja vértebra a vértebra. Repite." },
      { t: "Savasana", dur: "3 min", min: 3, pose: "Savasana",
        como: "Descansa boca arriba y observa cómo queda la espalda tras la práctica." },
    ] },
  { t: "Core y fuerza", lvl: "i", min: 25,
    pasos: [
      { t: "Saludo al sol", dur: "5 min", min: 5, pose: "Surya Namaskar",
        como: "Varios saludos al sol para calentar muñecas, hombros y abdomen." },
      { t: "Plancha", dur: "4 min", min: 4, pose: "Phalakasana",
        como: "Cuerpo recto de cabeza a talones, abdomen activo y manos bajo los hombros. Aguanta tandas de 30-45 segundos con descansos." },
      { t: "Barca", dur: "4 min", min: 4, pose: "Navasana",
        como: "Sentado, eleva las piernas y inclina el tronco atrás formando una V. Brazos paralelos al suelo. Si es mucho, dobla las rodillas." },
      { t: "Silla", dur: "4 min", min: 4, pose: "Utkatasana",
        como: "De pie, dobla las rodillas como si te sentaras en una silla invisible y sube los brazos. Peso en los talones." },
      { t: "Cobra", dur: "3 min", min: 3, pose: "Bhujangasana",
        como: "Compensa el trabajo abdominal abriendo el pecho: eleva el torso desde el suelo sin forzar el lumbar." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Relaja por completo el abdomen y respira hacia el vientre." },
    ] },
  { t: "Los tres guerreros", lvl: "i", min: 30,
    pasos: [
      { t: "Saludo al sol", dur: "6 min", min: 6, pose: "Surya Namaskar",
        como: "Calienta el cuerpo entero con saludos al sol fluidos." },
      { t: "Guerrero I", dur: "5 min", min: 5, pose: "Virabhadrasana I",
        como: "Zancada larga con el pie trasero apoyado en diagonal, caderas al frente y brazos al cielo. Mantén y cambia de lado." },
      { t: "Guerrero II", dur: "5 min", min: 5, pose: "Virabhadrasana II",
        como: "Abre la cadera hacia el lado, brazos en cruz y mirada sobre la mano delantera. Mantén y cambia de lado." },
      { t: "Guerrero III", dur: "5 min", min: 5, pose: "Virabhadrasana III",
        como: "Desde Guerrero I, vuelca el tronco hacia delante y eleva la pierna trasera hasta formar una T. Usa la pared si lo necesitas." },
      { t: "Triángulo", dur: "4 min", min: 4, pose: "Trikonasana",
        como: "Estira las dos piernas y alarga el tronco hacia delante antes de bajar la mano a la espinilla. Cambia de lado." },
      { t: "Savasana", dur: "5 min", min: 5, pose: "Savasana",
        como: "Suelta las piernas y deja que el pulso vuelva a la calma." },
    ] },
  { t: "Inversiones", lvl: "a", min: 35,
    pasos: [
      { t: "Saludo al sol", dur: "6 min", min: 6, pose: "Surya Namaskar",
        como: "Calienta a fondo: las inversiones piden hombros, muñecas y core despiertos." },
      { t: "Perro boca abajo", dur: "3 min", min: 3, pose: "Adho Mukha Svanasana",
        como: "Tu primera inversión suave: caderas arriba, cabeza relajada, peso repartido entre manos y pies." },
      { t: "La vela", dur: "6 min", min: 6, pose: "Salamba Sarvangasana",
        como: "Túmbate, eleva las piernas y la cadera y sostén la espalda con las manos. El peso va en hombros y brazos, nunca en el cuello." },
      { t: "El arado", dur: "4 min", min: 4, pose: "Halasana",
        como: "Desde la vela, baja los pies por detrás de la cabeza hacia el suelo. Si no llegan, déjalos a media altura. Sal despacio." },
      { t: "El pino", dur: "6 min", min: 6, pose: "Adho Mukha Vrksasana",
        como: "Frente a una pared, apoya las manos y sube las piernas con impulso controlado. Quédate el tiempo que controles y baja con suavidad." },
      { t: "Postura del niño", dur: "3 min", min: 3, pose: "Balasana",
        como: "Descansa y deja que la circulación se normalice tras las inversiones." },
      { t: "Savasana", dur: "7 min", min: 7, pose: "Savasana",
        como: "Relajación final larga: las inversiones piden un cierre tranquilo." },
    ] },
];
